/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Posicion {
	int x;
	int y;
};
typedef struct Posicion Posicion;

struct InfoAuto {
	Posicion posicion;
	char *tipoUber;
	float tarifa;
	char *placa;
};
typedef struct InfoAuto InfoAuto;

struct EstadoServicio {
	int viajesRealizados;
	int autosLibres;
	float gananciaTotal;
};
typedef struct EstadoServicio EstadoServicio;

struct Auto {
	bool_t disponible;
	Posicion posicion;
	char *tipoUber;
	float tarifa;
	char *placa;
	float ganancias;
};
typedef struct Auto Auto;

struct TerminarViajeArgs {
	Posicion posicionFinal;
	float costoViaje;
	char *placas;
};
typedef struct TerminarViajeArgs TerminarViajeArgs;

#define UBER_PROG 0x20000001
#define UBER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SolicitarViaje 1
extern  InfoAuto * solicitarviaje_1(Posicion *, CLIENT *);
extern  InfoAuto * solicitarviaje_1_svc(Posicion *, struct svc_req *);
#define TerminarViaje 2
extern  void * terminarviaje_1(TerminarViajeArgs *, CLIENT *);
extern  void * terminarviaje_1_svc(TerminarViajeArgs *, struct svc_req *);
#define estadoServicio 3
extern  EstadoServicio * estadoservicio_1(void *, CLIENT *);
extern  EstadoServicio * estadoservicio_1_svc(void *, struct svc_req *);
extern int uber_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SolicitarViaje 1
extern  InfoAuto * solicitarviaje_1();
extern  InfoAuto * solicitarviaje_1_svc();
#define TerminarViaje 2
extern  void * terminarviaje_1();
extern  void * terminarviaje_1_svc();
#define estadoServicio 3
extern  EstadoServicio * estadoservicio_1();
extern  EstadoServicio * estadoservicio_1_svc();
extern int uber_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Posicion (XDR *, Posicion*);
extern  bool_t xdr_InfoAuto (XDR *, InfoAuto*);
extern  bool_t xdr_EstadoServicio (XDR *, EstadoServicio*);
extern  bool_t xdr_Auto (XDR *, Auto*);
extern  bool_t xdr_TerminarViajeArgs (XDR *, TerminarViajeArgs*);

#else /* K&R C */
extern bool_t xdr_Posicion ();
extern bool_t xdr_InfoAuto ();
extern bool_t xdr_EstadoServicio ();
extern bool_t xdr_Auto ();
extern bool_t xdr_TerminarViajeArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
